### ISSUE TITLE
用终端打开报错

### ISSUE THREAD

**Issue by Pax-pi** [Doublefire-Chen/Lrcx_Creator#1]
总是显示“ImportError: No module named pydub”，似乎用不了

**Comment by Doublefire-Chen** [comment]
> 总是显示“ImportError: No module named pydub”，似乎用不了

朋友您好，很开心回答您的问题，因为这是我人生中收到的第一个Issue，感谢支持与信任，终于有人尝试运行我写的软件了，哈哈哈😁
您这个问题的出现是因为您的电脑缺少依赖包`pydub`，要解决这个问题，只需要打开终端输入`pip3 install pydub`，然后回车，等包装好了，重新运行软件，如果出现类似问题，解决方法同理。
祝您使用愉快，有什么问题欢迎反馈。

**Comment by CoderNixx** [comment]
真是个有趣的同学，你才刚上大学吗？祝学业顺遂，鹏程万里。

**Comment by Doublefire-Chen** [comment]
> 真是个有趣的同学，你才刚上大学吗？祝学业顺遂，鹏程万里。

谢谢你的祝福
我现在已经大三了，哈哈哈
一楼的问题应该解决了，我把issue关掉了
